// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents

SObject2Apex theSObject2Apex = new SObject2Apex('003Hp00002uCfy4IAC');
theSObject2Apex.getRecordTemplate();
